[config]
schemaVersion = "0.0.1"

[package]
# The name of the team you are publishing as
namespace = "Clazex"
# max 250 characters
description = "Make attack cooldown use Flea Brew reduced attack duration instead of the original duration as lower cap when Flea Brew is active."

# Replace this with a correct repo URL if the default is not accurate
websiteUrl = "https://github.com/Clazex/Silksong.FleaBrewCooldownFix"
containsNsfwContent = false


# dependencies are specified in the format AuthorName-PackageName = "version". You should always have at least BepInExPack_Silksong.
[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"


# in most cases you should not change this build block, or the first build.copy block; the dist and tmp directories are used
# by other build scripts
[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "./tmp"
target = "/"

# additional files and directories can be added to the package like this:
# [[build.copy]]
# source = "./CHANGELOG.md"
# target = "/"


[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong" ]

[publish.categories]
# available categories can be found at https://github.com/thunderstore-io/ecosystem-schema/blob/master/games/data/hollow-knight-silksong.yml
hollow-knight-silksong = [ "accessibility" ]
